ansible_python_interpreter: /usr/bin/python3
docker_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
docker_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo_template: docker.list.j2
docker_repo_dest: /etc/apt/sources.list.d/docker.list
