- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages }}"

- name: Download Docker GPG key
  get_url:
    url: "{{ docker_key_url }}"
    dest: /tmp/docker-archive-keyring.gpg

- name: Add Docker GPG key
  command: gpg --dearmor /tmp/docker-archive-keyring.gpg
  args:
    chdir: /usr/share/keyrings
  notify: Reload apt cache

- name: Copy Docker repository file
  template:
    src: "{{ docker_repo_template }}"
    dest: "{{ docker_repo_dest }}"
  notify: Reload apt cache

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Install npm
  npm:
    name: npm
    path: /home/ubuntu
    state: present

